import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Live Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen flex flex-col"}>
        <header className="flex justify-center py-6 text-5xl">
          {" "}
          <h1>Live Chat App</h1>
        </header>
        <div className="flex flex-col items-center justify-center flex-1  mb-20">
          {children}
        </div>
      </body>
    </html>
  );
}
